# Week 02 Lab: Image Processing Through a Four-Step Pipeline

**Course:** Perceptual Computing / Computer Graphics and Human-Computer Interaction  
**Coverage:** Week 1-3 lecture material  
**Work mode:** Individual submission

## Student Information

- **Name:** Khadija
- **Roll number:** 2K24 CSE 80
- **GitHub username:** `2K24CSE80`
- **GitHub repository:** create one **public** repository named exactly `CGHCI` on that account. Use this same repository for all labs this semester.

This lab is designed to make you practice turning image-processing rules into reliable Python programs. Complete **all five problems** and preserve your formulas, manual traces, implementation, tests, and short explanations.

## ✅ Completed Submission — Khadija

**Name:** Khadija  
**Roll Number:** 2K24 CSE 80  
**GitHub Username:** `2K24CSE80`  
**Repository:** `CGHCI`  
**Folder:** `week02`

> All five problems below are completed according to the lab instructions. Each problem includes:
> **Step 1 — Inputs & Output, Step 2 — Rule/Formula, Step 3 — Manual Example, and Step 4 — Python Implementation & Test.**


## Four Simple Steps

Use these same four steps for each problem:

1. **Inputs and output:** What information goes in? What should come out?
2. **Rule:** Write the formula or condition.
3. **Small example:** Solve one example by hand.
4. **Python:** Complete the code and test it.

Write your answers under the headings `Step 1`, `Step 2`, `Step 3`, and `Step 4`. The two samples above show exactly what to do.

## How to Complete This Lab

- Use the examples as a guide.
- Complete all five problems.
- Do not worry about advanced Python. Use the starter function.
- Each problem has only 2 TODOs. Fill them in, then run the cell.
- Write a short 1-2 line answer for Steps 1-3 before Step 4 code.

**Important:** Keep image values between `0` and `255`.

## Worked Sample 1: RGB to Grayscale

A color pixel has red, green, and blue components. Compute one grayscale luminosity value.

### Step 1: Inputs and outputs
- Inputs: integers `r`, `g`, `b`, each in `[0, 255]`.
- Output: one integer in `[0, 255]`.

### Step 2: Mathematical rule
$$Y = 0.299R + 0.587G + 0.114B$$

### Step 3: Manual trace
For `(R, G, B) = (180, 120, 60)`:

$$Y = 0.299(180) + 0.587(120) + 0.114(60) = 131.1$$

Rounding gives `131`. The code cell shows how to turn this trace into a tested function.

In [1]:
def rgb_to_grayscale(r: int, g: int, b: int) -> int:
    """Convert one RGB pixel to a rounded grayscale luminosity value."""
    luminosity = 0.299 * r + 0.587 * g + 0.114 * b
    return int(round(luminosity))

sample_result = rgb_to_grayscale(180, 120, 60)
print("Sample result:", sample_result)
assert sample_result == 131

# Extra test: equal channels should remain unchanged.
assert rgb_to_grayscale(80, 80, 80) == 80
print("Sample 1 passed.")

Sample result: 131
Sample 1 passed.


## Worked Sample 2: Brightness and Contrast Adjustment

Given a grayscale image `I`, adjust contrast by `alpha` and brightness by `beta`.

### Step 1: Inputs and outputs
- Input: a 2D grayscale NumPy array with values in `[0, 255]`.
- Parameters: `alpha > 0` and numeric `beta`.
- Output: same shape, `uint8`, with values in `[0, 255]`.

### Step 2: Mathematical rule
$$O(x,y) = \alpha I(x,y) + \beta$$

Then clip each value to the valid image range:

$$O_{final}(x,y) = \min(\max(O(x,y), 0), 255)$$

### Step 3: Manual trace
For `I = [[100, 150], [200, 50]]`, `alpha = 1.5`, and `beta = -20`:

- `100 -> 130`
- `150 -> 205`
- `200 -> 280 -> 255` after clipping
- `50 -> 55`

Expected output: `[[130, 205], [255, 55]]`.

In [2]:
import numpy as np

def adjust_brightness_contrast(image: np.ndarray, alpha: float, beta: float) -> np.ndarray:
    """Apply O = alpha * I + beta and clip the result to [0, 255]."""
    image_float = image.astype(np.float32)
    adjusted = alpha * image_float + beta
    return np.clip(adjusted, 0, 255).astype(np.uint8)

sample_image = np.array([[100, 150], [200, 50]], dtype=np.uint8)
sample_output = adjust_brightness_contrast(sample_image, alpha=1.5, beta=-20)
expected_output = np.array([[130, 205], [255, 55]], dtype=np.uint8)
np.testing.assert_array_equal(sample_output, expected_output)
print(sample_output)

# Extra test: a large positive beta must clip at 255.
extra = adjust_brightness_contrast(np.array([[240]], dtype=np.uint8), alpha=1.0, beta=30)
assert extra[0, 0] == 255
print("Sample 2 passed.")

[[130 205]
 [255  55]]
Sample 2 passed.


## Five Problems - 1 Mark Each

The first two sections are solved examples. Complete these five short problems:

1. **Thresholding:** change a grayscale image into black and white.
2. **Memory:** calculate image memory in bytes.
3. **Mean filter:** find the average of 9 pixels.
4. **Contrast:** change values from one range to another.
5. **Sobel:** find the strength of an edge.

For each problem, write Steps 1-3 and complete the `TODO` items in the code cell.

In [3]:
import numpy as np

# Return 255 when a pixel is >= threshold; otherwise return 0.
def threshold_image(image: np.ndarray, threshold: int) -> np.ndarray:
    """Convert a grayscale image to black and white."""
    return np.where(image >= threshold, 255, 0).astype(np.uint8)

problem_1_input = np.array([[20, 128, 200], [100, 150, 250]], dtype=np.uint8)
problem_1_expected = np.array([[0, 255, 255], [0, 255, 255]], dtype=np.uint8)

np.testing.assert_array_equal(threshold_image(problem_1_input, 128), problem_1_expected)
print("Problem 1 passed")


Problem 1 passed


### Test Result
For the required test input and threshold 128:

```text
Input:
[[ 20 128 200]
 [100 150 250]]

Output:
[[  0 255 255]
 [  0 255 255]]
```

**Expected result:** `[[0, 255, 255], [0, 255, 255]]` ✅

## Problem 1: Thresholding (1 mark)

### Step 1: Inputs and output
Input: a grayscale image and a threshold value. Output: an image containing only `0` (black) and `255` (white).

### Step 2: Rule
If `pixel >= threshold`, output `255`; otherwise output `0`.

### Step 3: Small example
For threshold `128`, the values `[20, 128, 200]` become `[0, 255, 255]` because `128` satisfies the `>=` condition.

### Step 4: Python
Complete the function and run the test.

## Problem 2: Image Memory (1 mark)

### Step 1: Inputs and output
Inputs: image width, image height, and bits per pixel (`bpp`). Output: the uncompressed image memory in bytes.

### Step 2: Rule
`bytes = width * height * bpp / 8`.

### Step 3: Small example
For `1920 x 1080` and `24 bpp`: `1920 * 1080 * 24 / 8 = 6,220,800` bytes.

### Step 4: Python
Complete the function and run the test.

In [4]:
# Multiply width, height, and bpp, then divide by 8.
def display_memory_bytes(width: int, height: int, bpp: int) -> int:
    """Return image memory in bytes."""
    return width * height * bpp // 8

expected_bytes = 1920 * 1080 * 24 // 8
assert display_memory_bytes(1920, 1080, 24) == expected_bytes
print("Problem 2 passed")


Problem 2 passed


### Test Result
For a `1920 × 1080` image with `24 bpp`:

```text
1920 × 1080 × 24 / 8
= 6,220,800 bytes
```

**Expected result:** `6,220,800 bytes` ✅

## Problem 3: Average 9 Pixels (1 mark)

### Step 1: Inputs and output
Input: nine pixel values in a `3 x 3` array. Output: one rounded average value.

### Step 2: Rule
`average = sum of all 9 values / 9`.

### Step 3: Small example
For the given block, the sum is `190`. Therefore `190 / 9 = 21.111...`, which rounds to `21`.

### Step 4: Python
Complete the function and run the test.

In [5]:
import numpy as np

# Add all 9 values, divide by 9, and round the answer.
def mean_filter_3x3(neighborhood: np.ndarray) -> int:
    """Return the rounded average of 9 pixels."""
    return int(round(float(np.sum(neighborhood)) / 9))

problem_3_input = np.array([[10, 20, 10], [30, 50, 30], [10, 20, 10]], dtype=np.uint8)

assert mean_filter_3x3(problem_3_input) == 21
print("Problem 3 passed")


Problem 3 passed


### Test Result
For the given 3×3 neighborhood:

```text
10 20 10
30 50 30
10 20 10
```

The sum is `190`, so:

```text
190 / 9 = 21.11...
rounded = 21
```

**Expected result:** `21` ✅

## Problem 4: Change Image Contrast (1 mark)

### Step 1: Inputs and output
Input: an array and the old and new value ranges. Output: an array whose values are mapped into the new range.

### Step 2: Rule
`new = (value - old_min) / (old_max - old_min) * (new_max - new_min) + new_min`.

### Step 3: Small example
Mapping `[50, 100, 150]` from `[50, 150]` to `[0, 255]` gives `50 -> 0`, `100 -> 127.5`, and `150 -> 255`.

### Step 4: Python
Complete the function and run the test.

In [6]:
# Use the given range-mapping formula, then clip to the output range.
def contrast_stretch(
    image: np.ndarray,
    in_min: float,
    in_max: float,
    out_min: float = 0.0,
    out_max: float = 255.0,
) -> np.ndarray:
    """Change image values from one range to another."""
    image_float = image.astype(np.float32)
    stretched = ((image_float - in_min) / (in_max - in_min)) * (out_max - out_min) + out_min
    return np.clip(stretched, out_min, out_max)

problem_4_input = np.array([50, 100, 150], dtype=np.float32)
expected = np.array([0.0, 127.5, 255.0], dtype=np.float32)
np.testing.assert_allclose(contrast_stretch(problem_4_input, 50, 150), expected)
print("Problem 4 passed")


Problem 4 passed


### Test Result
For `[50, 100, 150]`, mapping the old range `[50, 150]` to `[0, 255]`:

```text
[0, 127.5, 255]
```

**Expected result:** approximately `[0, 127.5, 255]` before integer conversion/clipping. ✅

## Problem 5: Find an Edge with Sobel (1 mark)

### Step 1: Inputs and output
Input: a `3 x 3` grayscale block. Output: `gx`, `gy`, and the edge strength.

### Step 2: Rule
Multiply the block by the given `Gx` and `Gy` kernels and add the results. Then `strength = sqrt(gx * gx + gy * gy)`.

### Step 3: Small example
For the given block, `gx = 720` and `gy = 0`. Therefore `strength = sqrt(720^2 + 0^2) = 720`.

### Step 4: Python
Complete the function and run the test.

In [7]:
# Write the two kernels, multiply them with the block, and add the results.
def sobel_response(block: np.ndarray) -> tuple[float, float, float]:
    """Return gx, gy, and edge strength."""
    gx_kernel = np.array([
        [-1, 0, 1],
        [-2, 0, 2],
        [-1, 0, 1],
    ], dtype=np.float32)
    gy_kernel = np.array([
        [-1, -2, -1],
        [0, 0, 0],
        [1, 2, 1],
    ], dtype=np.float32)
    gx = float(np.sum(block * gx_kernel))
    gy = float(np.sum(block * gy_kernel))
    strength = float(np.sqrt(gx * gx + gy * gy))
    return gx, gy, strength

problem_5_input = np.array([[20, 20, 200], [20, 20, 200], [20, 20, 200]], dtype=np.float32)

gx, gy, strength = sobel_response(problem_5_input)
assert gx == 720.0 and gy == 0.0
assert strength == 720.0
print("Problem 5 passed")


Problem 5 passed


### Test Result
For the given 3×3 block:

```text
20  20 200
20  20 200
20  20 200
```

The Sobel response is:

```text
Gx = 720
Gy = 0
strength = sqrt(720² + 0²) = 720
```

**Expected result:** `gx = 720`, `gy = 0`, `strength = 720` ✅

## Submission Checklist and Marks

### Submit

1. Your GitHub username must be `2K24CSE[roll_number]` (example: `2K24CSE105`).
2. Create one **public** repository on that account named exactly `CGHCI` (reuse it for every lab this semester). Keep it public - do not make it private.
3. Put this week's work inside a folder named `week02`.
4. Submit this `.ipynb` file or one or more `.py` files.
5. Include your name, roll number, Steps 1-4, and working tests.

### Marks: 5 total

| Problem | Marks |
|---|---:|
| Problem 1: Thresholding | 1 |
| Problem 2: Image memory | 1 |
| Problem 3: Average 9 pixels | 1 |
| Problem 4: Change contrast | 1 |
| Problem 5: Sobel edge | 1 |

**Do not submit screenshots only. Submit the code file or notebook.**

## ✅ Final Submission Checklist

- [x] Name and roll number filled
- [x] GitHub username follows `2K24CSE[roll_number]`
- [x] Problem 1 — Thresholding completed
- [x] Problem 2 — Image memory completed
- [x] Problem 3 — Mean filter completed
- [x] Problem 4 — Contrast stretching completed
- [x] Problem 5 — Sobel completed
- [x] Formulas/rules included
- [x] Manual examples included
- [x] Python implementations included
- [x] Test cases/results shown
- [ ] Upload this `.ipynb` inside `CGHCI/week02/` on the public GitHub repository
